### ISSUE TITLE
Get only needed transactions

### ISSUE THREAD

**Issue by Thenewchicken55** [Thenewchicken55/JES#14]
Similar to [issue13](https://github.com/Thenewchicken55/JES/issues/13#issue-2642179974), 

instead of getting all the transactions for all users, get only transactions for the one user

![image](https://github.com/user-attachments/assets/bca3df0e-3920-4be1-93ae-1044ebca53d5)

**Comment by javanm0** [comment]
Transactions are currently being filtered by user_id with the following SQL query:
`SELECT * FROM Transactions WHERE user_id = ? ORDER BY date DESC;`
